acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix:   /

eone_seo:
    resource: "@EoneSeoBundle/Resources/config/routing.yml"
    prefix:   /

eone_sonata_customization:
    resource: "@EoneSonataCustomizationBundle/Resources/config/routing.yml"
    prefix:   /

# Sonata admin with 'siteadmin' redirect
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

site_admin_root:
    pattern: /siteadmin
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true
site_admin_root_dash:
    pattern: /siteadmin/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true
        
# FOS User w/ Sonata
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_resetting:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_resetting.xml"
    prefix: /admin/resetting

#sonata_user_security:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
#
#sonata_user_profile:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /profile
#
#sonata_user_register:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
#    prefix: /register
#
#sonata_user_change_password:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
#    prefix: /profile
    