# Sonata configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
            
        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
            
sonata_admin:
    title:      Project name
    title_logo: bundles/eonesonatacustomization/images/project_logo.png
    options:
        #title_mode: 'both' #'single_image' or 'single_text' or 'both' (default)

    templates:
        layout:  EoneSonataCustomizationBundle::eone_standard_layout.html.twig

    security:
        handler: sonata.admin.security.handler.role
        #remove the master/operator (not working "as intended" with roles, & export
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
        
# FOS User w/ Sonata
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
    from_email:
        address:        %project.email.address%
        sender_name:    %project.email.sender%
        
sonata_user:
    impersonating:
        route:                sonata_admin_dashboard
    
# Misc
doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
            
twig:
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'