entrypoint:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Demo:entry }

home:
    pattern:  /{_locale}
    defaults: { _controller: AcmeDemoBundle:Demo:home }
    requirements:
        _locale:  %eone.locale.requirements%

switch_demo:
    pattern: /{_locale}/language
    defaults:
        _controller: AcmeDemoBundle:Demo:language
    requirements:
        _locale:  %eone.locale.requirements%