entrypoint:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Demo:entry }

home:
    pattern:  /{_locale}
    defaults: { _controller: AcmeDemoBundle:Demo:home }
    requirements:
        _locale:  %eone.locale.requirements%

menu_demo:
    pattern: /menu/{_locale}
    defaults:
        _controller: AcmeDemoBundle:Demo:menu