services:
    # Sonata Admin
    acme.admin.demo.news:
        class: Acme\DemoBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Demo, label: "News" }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\News
            - 'SonataAdminBundle:CRUD'
        calls:
            - [addChild, ["@acme.admin.demo.newsi18n"]]    
            
    acme.admin.demo.newsi18n:
        class: Acme\DemoBundle\Admin\NewsI18nAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Acme\DemoBundle\Entity\NewsI18n
            - 'EoneSonataCustomizationBundle:TranslatingAdmin'
            
    # menu renderer(s)
    acme.menu_renderer.language:
        class: Acme\DemoBundle\Menu\LanguageRenderer
        arguments: [%kernel.charset%]
        tags:
            - { name: knp_menu.renderer, alias: language }
